name: My Env Vars Workflow
on:
  push:
    branches:
      - 'master'
jobs:
  model-ci:
    env:
      DB_ADDRESS: my.database.address
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Build Model
        run: echo "Build Model in CI Pipeline"
  model-cd:
    needs: model-ci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Model
        run: echo "Deploy Model in CD Pipeline"